language: node_js

cache: 
  directories:
    - node_modules

node_js:
  - "8"

branches:
  only:
    - nest

install:
  - npm install

before_script:
  - mongo my_blog --eval 'db.createUser({user:"blog-server",pwd:"blog-server",roles:["readWrite"]});'

script:
  - npm run test:unit
  - npm run codecov

services:
  - mongodb